apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: iz6piu8t2-java-springboot
  janus-idp.io/tekton: iz6piu8t2-java-springboot
  backstage.io/kubernetes-id: iz6piu8t2-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: iz6piu8t2-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
